# Generated by Django 5.0.6 on 2024-06-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0003_alter_order_customer_alter_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/categories/'),
        ),
    ]
