# Generated by Django 5.0.6 on 2024-06-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0005_alter_category_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/resturant/categories/'),
        ),
    ]
