# Generated by Django 5.0.6 on 2024-06-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0006_alter_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_per_unit',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
