# Generated by Django 5.0.6 on 2024-06-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0007_remove_order_customer_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
