# Generated by Django 5.0.6 on 2024-06-18 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_remove_product_stocks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Item',
        ),
    ]
